name: 'kformpkg-action'
description: 'kformpkg-action, a release automation tool for kform providers and modules using oci artifacts'
author: 'kform'

inputs:
  kformpkgVersion:
    description: 'kform pkg version'
    default: 'latest'
    required: false
  kind:
    description: 'package kind (provider or module)'
    default: 'provider'
    required: true
  sourcePkgDir:
    description: 'Directory from which the package is sourced'
    default: config
    required: false
  targetPkgRegistryHostname:
    description: 'Hostname of the container registry e.g. ghcr.io where the oci artifact image is stored'
    required: true
  targetPkgNamespace:
    description: 'Name of the oci artifact package namespace, defaults to the owner/organization of the repository'
    required: false
  targetPkgName:
    description: 'Name of the oci artifact package (module or provider), defaults to the name of the repository'
    required: false
outputs:
  artifacts:
    description: 'Build result artifacts'

runs:
  using: 'node20'
  main: 'dist/index.js'